config/routes.rb
Rails.application.routes.draw do
  # Figure out how to make this work
  # namespace :wizards do
  #   resources :offerings do
  #     resources :build, controller: 'wizards/owner_offers'
  #   end
  # end


  get 'choose', to: 'choose#choose'
  post 'choose/owner', to: 'choose#as_owner'
  post 'choose/student', to: 'choose#as_student'

  get 'offerings/new', to: 'wizards/owner_offers#new'

  get 'students/iamstudent', to: 'students#new'
  post 'students/choose', to: 'students#choose', as: :starts_as_a_student

  get 'owners/iamowner', to: 'owners#new'
  post 'owners/choose', to: 'owners#choose', as: :starts_as_an_owner

  resources :owners
  resources :offerings do
    resources :build, controller: 'wizards/owner_offers', only: [:show, :update]
  end

  # resources :owners do
  #   resources :offerings do
  #     resources :build, controller: 'wizards/owner_offers'
  #   end
  # end
  #
  # resources :students
  #
  # resources :houses, shallow: true do
  #   resources :addresses, :rooms
  # end

  match '*path', controller: :application, action: :routing_error, via: :all
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :house
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :owner
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/consumable.rb
class Consumable < ActiveRecord::Base
  belongs_to :offering
end

app/models/house.rb
class House < ActiveRecord::Base
  belongs_to :offering

  has_one :address
  has_many :rooms

  accepts_nested_attributes_for :address
end

app/models/offer_internet.rb
class OfferInternet < ActiveRecord::Base
  belongs_to :room
end

app/models/offer_meal.rb
class OfferMeal < ActiveRecord::Base
  belongs_to :room
end

app/models/offer_pet.rb
class OfferPet < ActiveRecord::Base
  belongs_to :room
end

app/models/offer_smoke.rb
class OfferSmoke < ActiveRecord::Base
  belongs_to :room
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :owner

  has_one :house

  has_many :consumables

  accepts_nested_attributes_for :house
  accepts_nested_attributes_for :consumables

  default_scope { includes(:owner) }

  def active?
    self[:status] == 'active'
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  acts_as_commentable

  # validates :user, presence: true

  # delegate :email, :first_name, :last_name, :middle_name, :phone_number, to: :user
  # delegate :email=, :first_name=, :last_name=, :middle_name=, :phone_number=, to: :user

  default_scope { includes(:user) }
  has_one :user, as: :role # Need delete cascade here

  has_many :children
  has_many :pets
  has_many :offerings
  has_many :houses, through: :offerings

  has_many :comments, as: :commentable

  accepts_nested_attributes_for :pets
  accepts_nested_attributes_for :children
  accepts_nested_attributes_for :offerings

  def method_missing(m, *args)
    self.send(m, *args) if self.user.respond_to? :m
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
end

app/models/room.rb
class Room < ActiveRecord::Base
  acts_as_commentable
  acts_as_rateable

  belongs_to :house

  has_many :offer_meal
  has_one :offer_internet
  has_one :offer_smoke
  has_one :offer_pet

  accepts_nested_attributes_for :offer_meal
  accepts_nested_attributes_for :offer_internet
  accepts_nested_attributes_for :offer_smoke
  accepts_nested_attributes_for :offer_pet
end

app/models/student.rb
class Student < ActiveRecord::Base
  default_scope { includes(:user) }
  has_one :user, as: :role

  has_many :comments, as: :commentable
  def method_missing(m, *args)
    self.send(m, *args) if self.user.respond_to? :m
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLE = %w(Student Owner)

  belongs_to :role, polymorphic: true

  def login
    self[:first_name]
  end

  def has_role?
    self[:type].nil?
  end

  def turn_to_owner
    Owner.create(role)
  end

  ROLE.each do |role|
    logger.debug "Defining boolean checker for user role: #{role}"
    define_method("is_#{role.downcase}?") do
      self[:role_type] == role
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :fetch_owner, except: [:new, :choose]

  # # GET /owners/new
  def new; end

  def choose
    if current_user.role.nil?
      Owner.create.user = current_user
    else
      raise 'User is already associated with a student role, and cannot be reassigned' if current_user.role.is_student?
    end

    render 'starts_as_an_owner'
  end

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
    render json: @owners, status: :ok
  end

  # GET /owners/1
  # GET /owners/1.json
  # def show
  # end


  # # GET /owners/1/edit
  # def edit
  # end
  #
  # # POST /owners
  # # POST /owners.json
  # def create
  #   @owner = Owner.new(owner_params)
  #
  #   respond_to do |format|
  #     if @owner.save
  #       format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
  #       format.json { render :show, status: :created, location: @owner }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @owner.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /owners/1
  # # PATCH/PUT /owners/1.json
  # def update
  #   respond_to do |format|
  #     if @owner.update(owner_params)
  #       format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @owner }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @owner.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /owners/1
  # # DELETE /owners/1.json
  # def destroy
  #   @owner.destroy
  #   respond_to do |format|
  #     format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  private
  # Use callbacks to share common setup or constraints between actions.
  def fetch_owner
    @owner = Owner.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/choose_helper.rb
module ChooseHelper
end

app/helpers/houses_helper.rb
module HousesHelper
  def setup_house(owner)
    owner.tap do |o|
      o.pets.build if o.pets.empty?
      o.children.build if o.children.empty?
      o.offerings.build if o.offerings.empty?
    end

    owner.offerings.first.tap do |first_offer|
˜     first_offer.house = House.new if first_offer.house.nil?
      first_offer.house.address = Address.new if first_offer.house.address.nil?
    end

    owner
  end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.email %></td>
        <td><%= owner.phone_number %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>Welcome to the family,</h1>
<h3>At Hamijia, we strive to provide a homecoming and agreable environment to the students. We thank you for being part of us; and we hope that together, we can provide the best service to the students. Afterall, they are the one that has to keep up late at night to study, and their success determine our future.</h3>

<%= button_to 'Yes, I am an owner', starts_as_an_owner_path, class: 'btn btn-lg btn-primary', data: { confirm: 'We just have a few question to ask you before upgrading your account to an owners account. Note that you will not be able to revert this action.' } %>
<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
    <td>First name</td>
    <td><%= @owner.last_name %></td>
  </tr>
  <tr>
    <td>Last name</td>
    <td><%= @owner.last_name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @owner.email %></td>
  </tr>
  <tr>
    <td>Phone number</td>
    <td><%= @owner.phone_number %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/owners/starts_as_an_owner.html.erb
<h1>Welcome as an owner</h1>
<p>Together, we are sure to bring the best homestaying experience to our users</p>